sr-iov operator bases for 4.10
redhat-partner-solutions/vse-catalog pull request #2
Opened 2022-10-06 11:57 UTC by jnunyez

2022-10-06 14:40 UTC, natifridman reviewed
Looks good, I would also add a readme with an example of how to use it. Something like [this](https://github.com/redhat-cop/gitops-catalog/tree/main/advanced-cluster-management/operator)

2022-10-06 16:42 UTC, jnunyez commented
> Looks good, I would also add a readme with an example of how to use it. Something like [this](https://github.com/redhat-cop/gitops-catalog/tree/main/advanced-cluster-management/operator)

Added howto use it

2022-10-18 07:25 UTC, natifridman requested changes

2022-10-18 07:25 UTC, natifridman commented on components/apps/sriov-operator/README.md
> +* [4.10](overlays/4.10)
4.11 also
```suggestion
* [4.10](overlays/4.10)
* [4.11](overlays/4.11)
```

2022-10-18 15:24 UTC, natifridman approved these changes
LGTM, looks like you need to rebase with main branch

2022-10-19 17:28 UTC, merged